on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: current
          dest: '"${HOME}/racketdist-current-CS"'
          sudo: never
      - name: Install Resyntax
        run: raco pkg install --auto --installation resyntax
      - name: Check Resyntax is installed
        run: resyntax --help
