on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Autofix package
        uses: ./.github/actions/autofix
        with:
          package: compose-app
          owner: jackfirth
          repository: compose-app
