on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Install Racket and Resyntax
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: current
          dest: '"${HOME}/racketdist-current-CS"'
          sudo: never
          packages: resyntax
      - name: Check Resyntax is installed
        run: racket -l- resyntax/cli --help
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 999945
          private-key: ${{ secrets.RESYNTAX_APP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Install target package
        run: raco pkg install --auto --no-setup compose-app
      - name: Clone target package
        run: raco pkg update --clone cloned-package compose-app
      - name: Set current directory to cloned package
        run: cd cloned-package
      - name: Double check current directory
        run: ls
      - name: Double check git status
        run: git status
      - name: Configure Git username
        run: git config user.name "${{ steps.generate-token.outputs.app-slug }}[bot]"
      - name: Configure Git email
        run: git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com"
      - name: Create branch in target package repository
        run: git checkout -b autofix-${{ github.run_number }}-${{ github.run_attempt }}
      - name: Run Resyntax
        run: |
          racket -l- resyntax/cli fix \
            --package compose-app \
            --max-fixes 20 \
            --max-modified-files 10 \
            --max-modified-lines 300 \
            --max-pass-count 10 \
            --output-as-commit-message \
            --create-multiple-commits \
            >> /tmp/resyntax-output.txt
      - name: Create pull request
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { readFile, writeFile } = require('fs/promises');
            const commitMessageBody = await readFile('/tmp/resyntax-output.txt', { encoding: 'utf8' });
            const commitMessageTitle = "Automated Resyntax fixes";
            await exec.exec('git push --set-upstream origin autofix-${{ github.run_number }}-${{ github.run_attempt }}');
            await github.rest.pulls.create({
              owner: "jackfirth",
              repo: "compose-app",
              title: commitMessageTitle,
              head: "autofix-${{ github.run_number }}-${{ github.run_attempt }}",
              base: "jackfirth/compose-app",
              body: commitMessageBody,
              maintainer_can_modify: true,
            });
