on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Autofix package
        uses: ./.github/actions/autofix
        with:
          package: compose-app
          owner: jackfirth
          repository: compose-app
          private-key: ${{ secrets.RESYNTAX_APP_PRIVATE_KEY }}
